version: '3.7'


services:
  postgres_db:
    image: postgres:15.1-alpine
    restart: always
    env_file: .env
    ports:    # Set up ports exposed for other containers to connect to
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
