# Generated by Django 4.1.3 on 2022-12-20 20:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(default='00000000000', max_length=12, unique=True)),
                ('nome', models.CharField(default='', max_length=200)),
                ('genero', models.CharField(default='', max_length=100)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('rg', models.CharField(blank=True, max_length=15)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('numero_endereco', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=200)),
                ('celular', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=200)),
                ('celular_responsavel', models.CharField(blank=True, max_length=200)),
                ('telefone_comercial', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(default='00000000000', max_length=12, unique=True)),
                ('nome', models.CharField(default='', max_length=200)),
                ('genero', models.CharField(default='', max_length=100)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('rg', models.CharField(blank=True, max_length=15)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('numero_endereco', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=200)),
                ('celular', models.CharField(blank=True, max_length=200)),
                ('nome_mae', models.CharField(blank=True, max_length=200)),
                ('nome_pai', models.CharField(blank=True, max_length=200)),
                ('responsavel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web_api.responsavel')),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
    ]
