# Generated by Django 4.1.3 on 2022-12-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendido',
            name='ajuda_mensal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='ajuda_mensal_detalhe',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atendido',
            name='ajuda_mensal_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='alergia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='alergia_detalhe',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atendido',
            name='autorizado_buscar_01',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='atendido',
            name='autorizado_buscar_02',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='atendido',
            name='autorizado_buscar_03',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='atendido',
            name='autorizado_buscar_04',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='atendido',
            name='autorizado_embora_sozinho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='auxilio_governo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='motivo_status',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atendido',
            name='numero_nis',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='atendido',
            name='numero_sus',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='atendido',
            name='ocupacao_mae',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='atendido',
            name='ocupacao_outros',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='atendido',
            name='ocupacao_pai',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='atendido',
            name='pais_moram_juntos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='parentesco',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='problema_saude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='problema_saude_detalhe',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atendido',
            name='quantidade_residentes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='atendido',
            name='quantidade_residentes_assalariados',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='atendido',
            name='renda_per_capita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='residente_assalariado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='salario_mae',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='salario_outros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='salario_pai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='situacao_pais',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='atendido',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('desligado', 'Desligado')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='trauma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='uso_medicamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='uso_medicamento_detalhe',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='celular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Não Binário')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='numero_endereco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='rg',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='celular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='celular_responsavel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_binario', 'Não Binário')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='numero_endereco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='rg',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone_comercial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
