# Generated by Django 4.1.3 on 2022-12-20 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_atendido_ajuda_mensal_atendido_ajuda_mensal_detalhe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendido',
            old_name='parentesco',
            new_name='parentesco_responsavel',
        ),
        migrations.AddField(
            model_name='atendido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atendido',
            name='periodo_escolar',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('integral', 'Integral')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsavel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
