# Generated by Django 4.1.3 on 2022-12-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0003_rename_parentesco_atendido_parentesco_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='celular_responsavel',
        ),
        migrations.AddField(
            model_name='atendido',
            name='auxilio_governo_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
